import streamlit as st

st.set_page_config(
    page_title="Home"
)
st.title("Analyst Sandbox")

st.header("Introducing Analyst Sandbox, a plug-and-play solution for data analysis and visualization.")

st.write("With our easy-to-use platform built on Streamlit and Snowflake using the Snowpark connector, you can leverage the power of Snowflake computation without needing to code. Simply connect to your Snowflake account using your credentials and start exploring your data. You can provide data in terms of database view details or upload entire data files through our user-friendly UI. The data is stored in Snowflake, enabling quick processing whenever a transformation is applied. Our platform allows you to build interactive, resizable dashboards with visually appealing charts based on your analysis requirements. With our Workspace feature, you can identify your previous work and maintain different stages or different data altogether. A Workspace can connect to many tables to fetch and explore data, and it has its own dashboard to visualize data. Our infinite canvas Dashboard allows you to place all your visualizations together. These charts are resizable and draggable throughout the canvas, making it easy to create the perfect layout. You can also create charts and add them to the existing dashboard by using the create chart option. Creating a chart is simple. You can leverage the power of Snowpark for transformations and application of business logic. You can also provide the data either in the form of a JSON string, a external file, or a database view name. Just choose the type of chart you want to generate, and it will be displayed on the dashboard. As part of our hackathon submission, we've limited the project to visualizing data by temporarily storing it locally and providing only a limited range of charts, to demonstrate the potential for Analyst Sandbox. ")

st.markdown("<h4>Although we very recently began [ few days:) ], we have a greater vision to expand this solution by offering drag-and-drop functionality for fundamental BI transformations such as aggregations and filters. Additionally, we plan to incorporate NLP capabilities to analyze the data before visualization through the tool. This will provide a comprehensive solution for Data Analysts, Product Managers, and other Data Enthusiasts having to require no technical knowledge to effortlessly explore, analyze, and visualize data for proof of concepts while utilizing Snowflake's exceptional capabilities for Data Ingestion and Integration.</h4>",unsafe_allow_html=True)